#!/bin/sh
# list all cython files here
cython_files="laptop/blobs laptop/color"
for f in $cython_files
do
	echo "Compiling $f"
	cython $f.pyx
	gcc -shared -pthread -fPIC -fwrapv -O2 -w -fno-strict-aliasing -o $f.so -I/usr/include/python2.7 -I/usr/lib/python2.7/site-packages/numpy/core/include/ -I/usr/local/lib/python2.7/dist-packages/numpy/core/include/ $f.c
done
echo "Done with compilation"

